### ISSUE TITLE
Installing plugins

### ISSUE THREAD

**Issue by iodize6399** [escopecz/docker-compose-mautic#1]
Hello,

I'm trying to use your Dockerfile to build turnkey mautic image with inbuilt SES plugin. My Dockerfile looks something like this:

```
# Install dependencies needed for Composer to run and rebuild assets:
RUN apt-get update && apt-get install -y git curl npm && rm -rf /var/lib/apt/lists/*

# Get SES plugin using git:
RUN cd /var/www/html && \
    git clone https://github.com/pm-pmaas/etailors_amazon_ses.git docroot/plugins/AmazonSesBundle
```

To activate the plugin two more steps are required:

```
# Clear cache and reload/install plugin:
RUN cd /var/www/html && \
    php bin/console cache:clear && \
    php bin/console mautic:plugins:reload
```

However, I get SQL error, `In ExceptionConverter.php line 101: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused` during the build process. I believe this happens because during the build process, database is not fully configured and schemas are not initialized.

I can bypass this error by commenting out the RUN command above, manually attaching a shell to the live `mautic_web` container and executing the two commands directly within the container.

Is there a way to automate these steps in the Dockerfile so that the build process produces a turnkey Mautic image with the built-in plugin?

**Comment by escopecz** [comment]
Hey! Yes, you are right. The database is not even present in the docker container. It's in another container and is available once you run the docker compose and all containers get available. The cache isn't a problem as it is built every time you rebuilt the image. The `mautic:plugins:reload` command can be added to the script that runs once all the containers are available. In case of this repository it would be at the end of https://github.com/escopecz/docker-compose-mautic/blob/main/setup-dc.sh

**Comment by i13-ctflora** [comment]
@physx2494 - Did you ever get this working?  I have the git clone in my Dockerfile just before the FROM & COPY, and the Mautic:plugin:reload at the end of my setup-dc.sh.  The plugin is recognized, and I can enter everything I need for the DSN.  However, the test email always comes back with a 403 error, saying the request signature does not match, check the AWS Secret Access Key & signing method.  
But I know the credentials are fine because they work w/ SMTP no problem.
