### ISSUE TITLE
running docker-compose-mautic

### ISSUE THREAD

**Issue by harald-life-services** [escopecz/docker-compose-mautic#2]
Running the workflow I run into issues. They manifest in permission denied error. See the attached logfile.
[logs_31786061174.zip](https://github.com/user-attachments/files/18064741/logs_31786061174.zip)

_The docker info is as follows:_
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.30.3
    Path:     /root/.docker/cli-plugins/docker-compose

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 88bf19b2105c8b17560993bee28a01ddc2f97182
 runc version: v1.2.2-0-g7cb3632
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-126-generic
 Operating System: Ubuntu 22.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 957.4MiB
 Name: mautic-vps
 ID: 15a41ec3-d502-4d89-b585-01c41bb657ec
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

**Comment by escopecz** [comment]
Hi, I can't tell what to focus on. Is it this error?
```
2024-12-09T14:46:19.1753449Z [36;1m  echo "Error: Missing required environment variable: EMAIL_ADDRESS"[0m
```
See the readme on how to fix it.

**Comment by escopecz** [comment]
Another issue I can see in the logs:
```
2024-12-09T14:46:25.4535673Z [36;1m  echo "Error: Domain mautic.institut-leben.life does not point to the droplet IP."[0m
2024-12-09T14:46:25.4537632Z [36;1m  echo "To configure your DNS settings, access your domain registrar's DNS management page. Locate the DNS settings or DNS management section. You should create or update an A record with the following details: Name: @ (or your subdomain, e.g., www if your domain is www.example.com), Type: A, Value: 198.199.83.35. This change will point mautic.institut-leben.life to the IP address 198.199.83.35. Note that DNS changes can take up to 48 hours to propagate globally."[0m
```

**Comment by harald-life-services** [comment]
The email address and domain, did run without error.

I think we need to focus on the following:
![image](https://github.com/user-attachments/assets/2396a6ab-49be-4163-bc03-aa43752a82c6)

They lead to failure in:
![image](https://github.com/user-attachments/assets/04b68123-b85e-4ae3-9e40-8e89deef573c)

Everything else went through without error.
However no containers are installed, so I don't quite understand how _Open your Mautic Instance_ could work without error.

**Comment by harald-life-services** [comment]
perhaps helpful in determining where the workflow stopped:
- the home directory is empty
- the setup-dc.log in /var/log contains one line: SCRIPT_AFTER:: command not found
- the ~ directory only includes a snap directory
- the var/www directory only holds the html that is displayed when visiting http://mautic.institut-leben.life
- trying to run docker compose from ~ in droplet console results in _no configuration file provide: not found_ message

**Comment by escopecz** [comment]
I was consulting with an AI:

> The error message indicates that there is an issue with loading the SSH key due to an error in the libcrypto library. This can happen if the SSH key is not correctly formatted or if there is an issue with the environment in which the GitHub Actions runner is executing.

> Make sure that the SSH key is correctly formatted and does not contain any extraneous characters or whitespace.

**Comment by harald-life-services** [comment]
OK, I got that sorted. It took me a while to figure out that a static SSH key needed to be generated. 
ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f my-github-actions-key did the trick in the end.

Now, the workflow runs through without errors. However, Mautic is still not running. It could have to do with a couple of warnings generated?
![image](https://github.com/user-attachments/assets/1b78c68e-ec1b-4074-b53a-666fa3ab2a6f)

Can you figure out what needs to be changed?

**Comment by escopecz** [comment]
The output from the remote script should be stored in [this file](https://github.com/escopecz/docker-compose-mautic/blob/main/.github/workflows/deploy.yml#L145C55-L145C67) and then the log is downloaded from the server to GH actions and uploaded as an artifact:

https://github.com/escopecz/docker-compose-mautic/blob/main/.github/workflows/deploy.yml#L157-L170

So you should see it in the GH Action summary for download and inspection.

**Comment by harald-life-services** [comment]
Hi John,

Thank you for your help.

As it turns out my Mautic password contained a character that the script didn’t like. Changing the password did the trick in the end.

Best regards,

Harald

 

Von: John Linhart ***@***.***> 
Gesendet: Donnerstag, 12. Dezember 2024 13:07
An: escopecz/docker-compose-mautic ***@***.***>
Cc: harald-life-services ***@***.***>; Author ***@***.***>
Betreff: Re: [escopecz/docker-compose-mautic] running docker-compose-mautic (Issue #2)

 

The output from the remote script should be stored in this file <https://github.com/escopecz/docker-compose-mautic/blob/main/.github/workflows/deploy.yml#L145C55-L145C67>  and then the log is downloaded from the server to GH actions and uploaded as an artifact:

https://github.com/escopecz/docker-compose-mautic/blob/main/.github/workflows/deploy.yml#L157-L170

So you should see it in the GH Action summary for download and inspection.

**Comment by escopecz** [comment]
Awesome! Thanks for your feedback! Please send me a PR with the readme updates in places where you got stuck and more info would be helpful so others (and the future us) will get smoother deployments.

**Comment by harald-life-services** [comment]
Hi John,
Here are the issues I had with their solutions:
1) Couldn't get going to start with, as the trigger in the deploy.yml (on push) did not work. Got around it by editing the deploy.yml and change it back to the original.
2) It was not clear what the private ssh key format should be. In the beginning I messed around with putty as suggested, but that did not get me where I wanted. In the end the ssh-keygen -t rsa -b 4096 -C "[your_email@example.com](mailto:your_email@example.com)" -f my-github-actions-key produced the key in the required format.
3) Finally a "(" character in my mautic password messed up the script. So make sure you don't use special characters in the PW keyphrase that could be misinterpreted in the script.
