### ISSUE TITLE
installing plugin

### ISSUE THREAD

**Issue by harald-life-services** [escopecz/docker-compose-mautic#3]
Hi John,
If I want to install a plugin with composer, how do I find the correct package name? For instance with the etailors/mautic-amazon-ses plugin, I get an error message:
failed to solve: process "/bin/sh -c cd /var/www/html &&     COMPOSER_ALLOW_SUPERUSER=1 COMPOSER_PROCESS_TIMEOUT=10000  vendor/bin/composer require etailors/mautic-amazon-ses:^1.0 --no-scripts --no-interaction" did not complete successfully: exit code: 2

Sorry, I am not too versed with Composer I am afraid.

**Comment by escopecz** [comment]
This is a good question. The correct name is written in the `composer.json` file in the root directory of the plugin. In your case you are using the right name:

https://github.com/pm-pmaas/etailors_amazon_ses/blob/main/composer.json#L2

However, in order for Composer to find the package, it must be published at packagist.org. I don't see it there:

https://packagist.org/?query=mautic-amazon-ses

So either choose some plugin that is published there, ask the author to publish it or you can [tell Composer to look for it in the Github repository](https://getcomposer.org/doc/05-repositories.md#repository) but you'd have to manually edit the `composer.json` file to do that so try to explore the first 2 options.

**Comment by harald-life-services** [comment]
OK, so I did try another plugin that was published. The log does not show any errors now.

However, the page does not load anymore: ERR_TOO_MANY_REDIRECTS

 

Any idea what went wrong here?

 

Thanks.

H:)

 

Von: John Linhart ***@***.***> 
Gesendet: Mittwoch, 18. Dezember 2024 17:21
An: escopecz/docker-compose-mautic ***@***.***>
Cc: harald-life-services ***@***.***>; Author ***@***.***>
Betreff: Re: [escopecz/docker-compose-mautic] installing plugin (Issue #3)

 

This is a good question. The correct name is written in the composer.json file in the root directory of the plugin. In your case you are using the right name:

https://github.com/pm-pmaas/etailors_amazon_ses/blob/main/composer.json#L2

However, in order for Composer to find the package, it must be published at packagist.org. I don't see it there:

https://packagist.org/?query=mautic-amazon-ses

So either choose some plugin that is published there, ask the author to publish it or you can tell Composer to look for it in the Github repository <https://getcomposer.org/doc/05-repositories.md#repository>  but you'd have to manually edit the composer.json file to do that so try to explore the first 2 options.

**Comment by escopecz** [comment]
That would be for a discussion with the plugin developer. I can't tell from the error message.
